# .github/workflows/deploy.yml

name: Deploy Hugo Site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "${{ env.HUGO_VERSION }}"

      # ===============================================================
      #  ↓↓↓ 我们最关键的调试步骤 ↓↓↓
      # ===============================================================
      - name: Debug Project Structure and Config
        run: |
          echo ">>> Listing all files in the repository:"
          find . -print
          echo " "
          echo ">>> Displaying content of hugo.toml:"
          # We use `cat || true` in case the file doesn't exist for some reason
          cat hugo.toml || true
          echo " "
          echo ">>> Displaying content of config/_default/config.toml (if it exists):"
          cat config/_default/config.toml || true
          echo " "

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
